services:
    go-city-dev:
        container_name: go-city-dev
        build:
            context: ../
            dockerfile: ./Dockerfile
        volumes:
            - ..:/workspaces/go-city:cached
            - /dev:/dev:rw
            - ${XAUTHORITY:-${HOME}/.Xauthority}:/tmp/.Xauthority
        environment:
            DISPLAY: ${DISPLAY}
            XAUTHORITY: /tmp/.Xauthority
        ipc: host
        network_mode: "host"
        privileged: true
        cap_add:
            - SYS_ADMIN
            # Allows container process to change process priority
            - SYS_NICE
            # [Optional] Required for ptrace-based debuggers like C++, Go, and Rust
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined
        ulimits:
            rtprio: 99
        command: ""
        entrypoint: /bin/bash -c "sleep inf"
        group_add:
            - dialout
            - plugdev
            - video
            - audio